version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: main
      MYSQL_USER: testando
      MYSQL_PASSWORD: teste@@
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: 
        - api-network

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
    networks: 
        - api-network

volumes:
  mariadb_data:

networks:
  api-network:
    driver: bridge
